### ISSUE TITLE
update HOEK

### ISSUE THREAD

**Issue by RicardoUsbeck** [dice-group/ida#15]
![image](https://user-images.githubusercontent.com/4354740/41896547-2c1b266e-7925-11e8-8b1e-e05268eaf574.png)

**Comment by nikit91** [comment]
@RicardoUsbeck 

This vulnerability issue is caused because the sub-dependencies of "karma" require the "hoek" version 2.x.x . (ref: https://github.com/karma-runner/karma/issues/2994)

It can only be resolved once "karma" updates its own package and makes it available in the update.

We run "npm update" on our project from time to time and hence this issue will be resolved automatically once it is closed by "karma".

**Comment by nikit91** [comment]
Closing and tagging this issue to https://github.com/dice-group/ida/issues/66
